# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_PitynaUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 541)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelDropImg = QtWidgets.QLabel(self.centralwidget)
        self.LabelDropImg.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.LabelDropImg.setText("")
        self.LabelDropImg.setObjectName("LabelDropImg")
        self.LabelShowImg = QtWidgets.QLabel(self.centralwidget)
        self.LabelShowImg.setGeometry(QtCore.QRect(300, 0, 500, 300))
        self.LabelShowImg.setText("")
        self.LabelShowImg.setPixmap(QtGui.QPixmap(":/re/talk.gif"))
        self.LabelShowImg.setObjectName("LabelShowImg")
        self.LabelResponse = QtWidgets.QLabel(self.centralwidget)
        self.LabelResponse.setGeometry(QtCore.QRect(0, 300, 800, 200))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.LabelResponse.setFont(font)
        self.LabelResponse.setFrameShape(QtWidgets.QFrame.Box)
        self.LabelResponse.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.LabelResponse.setText("")
        self.LabelResponse.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelResponse.setObjectName("LabelResponse")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MenuClose = QtWidgets.QAction(MainWindow)
        self.MenuClose.setObjectName("MenuClose")
        self.menu.addAction(self.MenuClose)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.MenuClose.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "ファイル"))
        self.MenuClose.setText(_translate("MainWindow", "閉じる"))
import qt_resource_rc
